-- Lung Disease AI Database Schema - Row Level Security (RLS) Policies
-- Generated by LungAI System

-- ==========================================
-- 1. Enable RLS on all tables
-- ==========================================
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE xray_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE vitals ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 2. Define App Role (if not using Supabase defaults)
-- Usually, Supabase uses 'anon' and 'authenticated' roles.
-- For a Flask app connecting via a service role connecting string, 
-- it often bypasses RLS. To enforce it at the DB level for the API:
-- ==========================================

-- Policy for Users table
-- Users can only read and update their own record
CREATE POLICY "Users can view own record" ON users
    FOR SELECT USING (auth.uid()::text = id::text);

-- Policy for Patients table
-- Doctors can view all patients. Patients can only view themselves.
-- Note: Requires application logic to set the correct role context in Postgres, 
-- or use Supabase Auth directly. For a standard Flask app, we'll allow full access 
-- if accessed via the service role, or tie it to the authenticated user's patient_id.
CREATE POLICY "Allow full access for service role" ON patients
    FOR ALL USING (true);

-- Policy for XRay Reports
CREATE POLICY "Allow full access to reports for service role" ON xray_reports
    FOR ALL USING (true);

-- Policy for Vitals
CREATE POLICY "Allow full access to vitals for service role" ON vitals
    FOR ALL USING (true);

-- Note: Because your Flask application connects to Supabase using the 
-- direct PostgreSQL connection string (which acts as a superuser/service role),
-- RLS policies created here are bypassed by default when queried from Flask.
-- To strictly enforce RLS per-user, Flask must authenticate via the Supabase 
-- REST API (using supabase-py) and pass the user's JWT token, OR execute 
-- `set_config('request.jwt.claim.sub', user_id, true)` before each query.

SELECT 'RLS enabled on all tables.' AS Status;
