-- Lung Disease AI Database Schema for Supabase PostgreSQL
-- Generated by LungAI System

-- Create Users Table (Authentication)
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(120) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    patient_id INTEGER, -- FK added below
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create Patients Table (Demographics)
CREATE TABLE IF NOT EXISTS patients (
    id SERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    age INTEGER NOT NULL,
    gender VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add Foreign Key to Users table
ALTER TABLE users ADD CONSTRAINT fk_user_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE SET NULL;

-- Create XRay Reports Table (AI Predictions & History)
CREATE TABLE IF NOT EXISTS xray_reports (
    id SERIAL PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    image_path VARCHAR(255) NOT NULL,
    prediction VARCHAR(50) NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    severity VARCHAR(20),
    heatmap_path VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create Vitals Table (IoT Time-Series Data)
CREATE TABLE IF NOT EXISTS vitals (
    id SERIAL PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    spo2 DOUBLE PRECISION NOT NULL,
    temperature DOUBLE PRECISION NOT NULL,
    heart_rate INTEGER NOT NULL,
    device_id VARCHAR(50),
    recorded_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create Indexes for foreign keys and common queries
CREATE INDEX IF NOT EXISTS idx_xray_reports_patient ON xray_reports(patient_id);
CREATE INDEX IF NOT EXISTS idx_vitals_patient ON vitals(patient_id);
CREATE INDEX IF NOT EXISTS idx_vitals_recorded_at ON vitals(recorded_at);

-- Output success message
SELECT 'Database schema initialized successfully for LungAI.' AS Status;
